### ISSUE TITLE
5) ¿Cómo se aplica las Modulaciones Digitales ASK, FSK, PSK en sistemas IoT?. ¿Dónde se usa?. Ejemplifique

### ISSUE THREAD

**Issue by Leytonale** [ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tarea2-grupo-5#5]
-Fuente sugerida: Cambria, Calibri, Helvetica o Times New Roman.
-Tamaño sugerido: 12 para el cuerpo del texto, 16 para los títulos principales, 14 para los títulos secundarios y 12 para los subtítulos.
-Se sugiere entregar en formato PDF.

**Comment by Domi74** [comment]
el trabajo 2 fue entregado
